system_codes = [{"id": "C", "name": "Commodore 64"},
			    {"id": "D", "name": "GameCube Demo"},
			   	{"id": "E", "name": "Arcade"},
			   	{"id": "F", "name": "NES"},
			   	{"id": "G", "name": "GameCube"},
			   	{"id": "H", "name": "Wii channel"},
			   	{"id": "J", "name": "SNES"},
			   	{"id": "L", "name": "Sega Master System"},
			   	{"id": "M", "name": "Sega Genesis"},
			   	{"id": "N", "name": "N64"},
			   	{"id": "P", "name": "TurboGrafx-16"},
			   	{"id": "Q", "name": "TurboGrafx-16"},
			   	{"id": "R", "name": "Wii"},
			   	{"id": "S", "name": "Wii"},
			   	{"id": "W", "name": "WiiWare"},
			   	{"id": "X", "name": "MSX"},
			   	{"id": "r", "name": "Wii DLC"},
			   	{"id": "s", "name": "Wii DLC"},
			   	{"id": "w", "name": "Wii DLC"}]

region_codes = [{"id": "A", "name": "System Wii Channel"},
			   	{"id": "B", "name": "NTSC"},
			   	{"id": "D", "name": "Germany"},
                {"id": "E", "name": "NTSC"},
                {"id": "F", "name": "France"},
                {"id": "H", "name": "Netherlands"},
                {"id": "I", "name": "Italy"},
                {"id": "J", "name": "Japan"},
                {"id": "K", "name": "Korea"},
                {"id": "L", "name": "PAL"},
                {"id": "M", "name": "PAL"},
                {"id": "N", "name": "NTSC"},
                {"id": "P", "name": "PAL"},
                {"id": "Q", "name": "Korea"},
                {"id": "R", "name": "Russia"},
                {"id": "S", "name": "Spain"},
                {"id": "T", "name": "Korea"},
                {"id": "U", "name": "PAL"},
                {"id": "V", "name": "Scandinavia"},
                {"id": "W", "name": "Taiwan"},
                {"id": "X", "name": "NTSC"},
                {"id": "Y", "name": "NTSC"},
                {"id": "Z", "name": "NTSC"}]

publisher_codes = [{"id": "00", "name": "Nintendo"},
                   {"id": "01", "name": "Nintendo"},
                   {"id": "08", "name": "Capcom"},
                   {"id": "0A", "name": "Jaleco Entertainment"},
                   {"id": "0L", "name": "Warashi"},
                   {"id": "0M", "name": "Entertainment Software Publishing"},
                   {"id": "0Q", "name": "IE Institute"},
                   {"id": "13", "name": "Electronic Arts"},
                   {"id": "18", "name": "Hudson Entertainment"},
                   {"id": "1K", "name": "Titus Software"},
                   {"id": "20", "name": "DSI Games"}]
